server:
  port: 8000
  servlet:
    context-path: / #http://localhost:/blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class-name: org.mariadb.jdbc.Driver
    url:  jdbc:mysql://localhost:3307/blog?serverTimezone=Asia/Seoul
    # url: jdbc:mariadb://localhost:3306/blog?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: bonsimony
    password: bonsimony5678
    # password: bonsimony1234 
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update #create #update #none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #PhysicalNamingStrategyStandardImpl :  변수명 그대로 테이블 칼럼으로 만들어준다.
      use-new-id-generator-mappings: false #JPA의 기본전략(넘버링전략)을 따라가지 않겠다.
    show-sql: true #콘솔창에 sql 실행문을 보여준다.
    properties:
      hibernate.format_sql: false #콘솔창에 일자로 보여주는 것이 아닌 수직으로 이쁘게 보여준다.

  jackson:
    serialization:
      fail-on-empty-beans: false
            
cos:
  key: cos1234